### ISSUE TITLE
Option to disable notifications?

### ISSUE THREAD

**Issue by orschiro** [ewnd9/record-desktop#22]
Dear @ewnd9, 

What a great screencast gif recorder!

Thank you. 

Could we add an option to disable notification bubbles?

They get in my way when recording my screen. 

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/22432418/1c0d6eb0-e715-11e6-90c2-1b68260adc25.png)

**Comment by ewnd9** [comment]
Yep, totally make sense as I implemented them mostly as debug log :+1:

I will try to find time on the weekend to resolve this. Meanwhile, I recommend you to find a way to temporarily disable the notification system while recording a gif.

**Comment by orschiro** [comment]
Thank you! :-)

Meanwhile one can use this to block notifications: 

http://askubuntu.com/questions/769948/is-there-a-dont-disturb-option-to-temporarily-hide-notifications-like-on-mac

**Comment by ewnd9** [comment]
Switch is at the bottom of the settings page.

You can update via [npm](http://npmjs.com/package/record-desktop) or by downloading .deb from [releases page](https://github.com/ewnd9/record-desktop/releases) 

![image](https://cloud.githubusercontent.com/assets/1713789/22624589/60c57eb2-ebbb-11e6-8924-9faaf9ecc845.png)

**Comment by orschiro** [comment]
Wow, this is great. Thank you! :-)
