### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by chriad** [ewnd9/record-desktop#27]
Hi, I could install record-dektop but when I launch it it just shows a blank window saying "Loading...".

I installed as described in the "Install" section of the README.

$ node --version
v7.9.0

$ npm --version
4.5.0

$ cat /etc/issue
Ubuntu 16.10 \n \l

$ ps aux|grep record-desktop
chriad   18495  0.8  1.3 414788 54912 pts/18   Sl+  10:49   0:00 /usr/lib/node_modules/record-desktop/node_modules/electron-prebuilt/dist/electron --type=gpu-process --channel=18470.0.509293648 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=2,51,63 --disable-gl-extensions=GL_ARB_occlusion_query GL_ARB_occlusion_query2 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0116 --gpu-driver-vendor --gpu-driver-version --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
chriad   18503  4.9  1.8 1021240 73680 pts/18  Sl+  10:49   0:00 /usr/lib/node_modules/record-desktop/node_modules/electron-prebuilt/dist/electron --type=renderer --no-sandbox --lang=en-US --node-integration=true --num-raster-threads=2 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --channel=18470.1.1375385556 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd

$ /usr/lib/node_modules/record-desktop/node_modules/electron-prebuilt/dist/electron --version
v0.36.12

I would appreciate your help!

**Comment by ewnd9** [comment]
Hi, thanks for taking interest in `record-desktop`

Please, paste logs from `/tmp/record-desktop` 

```sh
$ cat /tmp/record-desktop
```

**Comment by ewnd9** [comment]
Also, you could try to check the error cause in [the development mode](https://github.com/ewnd9/record-desktop#development)

```sh
$ npm run build:watch
$ npm start
```

There will be Developers Tools on the right which will show the error message

**Comment by chriad** [comment]
> Please, paste logs from /tmp/record-desktop

There is no such file...

> $ npm run build:watch

This failed, here is the output of the log:

> $ npm run build:watch

```
$ npm run build:watch

> record-desktop@0.5.1 build:watch /usr/lib/node_modules/record-desktop
> npm-run-all --parallel build:electron:watch build:frontend:watch


> record-desktop@0.5.1 build:electron:watch /usr/lib/node_modules/record-desktop
> babel --watch -d dist/ src/


> record-desktop@0.5.1 build:frontend:watch /usr/lib/node_modules/record-desktop
> webpack-dev-server

 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /usr/lib/node_modules/record-desktop
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.15.0
Time: 78ms
webpack: Compiled successfully.
src/ doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! record-desktop@0.5.1 build:electron:watch: `babel --watch -d dist/ src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the record-desktop@0.5.1 build:electron:watch script 'babel --watch -d dist/ src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the record-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel --watch -d dist/ src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs record-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls record-desktop
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chriad/.npm/_logs/2017-04-22T07_22_35_735Z-debug.log
ERROR: build:electron:watch: None-Zero Exit(2);
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! record-desktop@0.5.1 build:watch: `npm-run-all --parallel build:electron:watch build:frontend:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the record-desktop@0.5.1 build:watch script 'npm-run-all --parallel build:electron:watch build:frontend:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the record-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel build:electron:watch build:frontend:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs record-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls record-desktop
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chriad/.npm/_logs/2017-04-22T07_22_35_826Z-debug.log

``` 

> $ npm start

![image](https://cloud.githubusercontent.com/assets/4353001/25302459/c70d44f2-273e-11e7-87fd-7efa8f00d878.png)

I don't really have experience with node/npm so I don't know exactly what to look for. It seems the app cannot connect to localhost, might be some misconfiguration on my system?...

**Comment by ewnd9** [comment]
I installed locally and now see the issue

You can either install a missing module

```sh
$ cd /usr/lib/node_modules/record-desktop 
$ sudo npm i electron-localshortcut 
```

or download and install the Debian package from the [releases page](https://github.com/ewnd9/record-desktop/releases). (It's not in the readme, I will update it after ending this comment) 

```sh
$ cd ~/Downloads
$ sudo dpkg -i record-desktop_v0.5.1_amd64.deb
```

If the issue is not resolved, try to open Developer Tools (ctrl+shift+i or in the top menu: View -> Toggle Developer Tools) from production build and include a screenshot 

```sh
$ /usr/lib/node_modules/record-desktop/app.js
```
---

I'm not sure about the necessity of sudo on the second command. If I recall correctly to change anything in `/usr/lib` you need the root permission. I recommend to setup `npm` for installing global packages to your home folder instead by [this guide](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)

**Comment by ewnd9** [comment]
About the development setup you had errors with: you was needed to run them in a cloned locally repository, sorry for not mentioning this

**Comment by chriad** [comment]
> You can either install a missing module
> 
> > $ cd /usr/lib/node_modules/record-desktop 
> > $ sudo npm i electron-localshortcut 

I did install the missing module, now the error message has changed:

![image](https://cloud.githubusercontent.com/assets/4353001/25324015/9699f3f2-28c3-11e7-9c4d-87dbbfa66e3f.png)

When installing the *.deb package, the following error results when trying to launch the application:
```

$ record-desktop 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/usr/share/record-desktop/resources/app/dist/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Object.<anonymous> (/usr/share/record-desktop/resources/atom.asar/browser/init.js:158:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
```

Then I tried to launch the app manually with

`$ /usr/share/record-desktop/resources/app/app.js`

This resulted in the error that the module `electron-prebuilt` could not be found:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'electron-prebuilt'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/record-desktop/resources/app/app.js:3:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

When I install the missing `electron-prebuilt` module, the app doesn't start and the error is:

```
$ /usr/share/record-desktop/resources/app/app.js
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.12/docs

Error: Cannot find module '/usr/share/record-desktop/resources/app'
```

Hope this helps!

**Comment by ewnd9** [comment]
Probably now there is an issue with two apps installed at the same time

So let's try from the beginning (running from sources)

Please do the following:

```sh
$ git clone https://github.com/ewnd9/record-desktop.git /tmp/repo
$ cd /tmp/repo
$ npm install
$ npm run build # I've got an error from UglifyJs, but it's only minifying step, not required for functioning
$ node app
```

If everything is alright you should uninstall the version from npm, and, hopefully, the deb version will work 

```sh
$ sudo npm uninstall record-desktop -g
```

**Comment by ewnd9** [comment]
Feel free to reopen if the problem is still there.
