### ISSUE TITLE
Missing shortcuts error

### ISSUE THREAD

**Issue by jfmengels** [ewnd9/record-desktop#6]
Hi! When I'm launching the `record-desktop`, I'm getting the following error:

```
info: missing shortcut for RECORD_AREA
info: missing shortcut for RECORD_ACTIVE
info: missing shortcut for STOP
info: missing shortcut for SCREEN_AREA
info: missing shortcut for SCREEN_ACTIVE
```
I'm using, Node.js v5.7.0, linux 4.2.0-30-generic, Ubuntu 15.10 and I installed what was indicated in the README. Let me know if you want more info :)

**Comment by ewnd9** [comment]
Hi. Sorry, it's just a debug message (no shortcuts by default), I'll delete them.  

What version of `record-desktop` do you have? I added showing settings window with shortcuts setup on the first run in `v0.1.0` and the latest version is `v0.2.3`. Is any window popped up when you started the app?

**Comment by jfmengels** [comment]
I think I had the latest version as I installed it right before trying, so it must have been `v0.2.3`. No windows popped up and I had no icon in the tray (I think that's what it's called)

I installed `v0.3.0` just now, and it works better for some reason. Now I'm getting a tray icon, which I can open, and I have been able to create gifs \o/ Nice work on this! :D

That said, it didn't open a window when I started the app (not even the first time), but maybe that's beause I had already did it in a previous version?

**Comment by ewnd9** [comment]
> Nice work on this! :D

Thanks :-)

> That said, it didn't open a window when I started the app (not even the first time), but maybe that's because I had already opened it it in a previous version?

There is the simple logic (https://github.com/ewnd9/record-desktop/blob/1899263d2287333239267769f9fb8ceae40bc956/src/main.js#L56-L58) to show window on start only when shortcuts are not set.

---

Did you try making screenshots with shadow background (new function in `v0.3.0`)? What do you think about it? What did you use before to take screenshots?
